apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-router
  namespace: default
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: utwo/nginx-proxy:v1
          name: nginx
