apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  ports:
    - name: nginx-sandbox-port
      port: 80
      protocol: TCP
      targetPort: 80
    - name: nginx-vscode-port
      port: 81
      protocol: TCP
      targetPort: 81
  selector:
    app: nginx
  sessionAffinity: None
  type: NodePort
