apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    {{- include "playground-sandbox.labels" . | nindent 4 }}
    app: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "playground-sandbox.selectorLabels" . | nindent 6 }}
      app: backend
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "playground-sandbox.labels" . | nindent 8 }}
        app: backend
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          workingDir: /app
          env:
            {{- toYaml .Values.backend.env | nindent 12 }}
            - name: SANDBOX_NAMESPACE
              value: {{ .Values.sandboxNamespace }}
            - name: SERVICE_VERSION
              value: {{ .Values.backend.image.tag | default .Chart.AppVersion }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          {{- if .Values.backend.serviceMonitor.enabled }}
            - name: metrics
              containerPort: 9464
              protocol: TCP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/projects
              name: project-pv-storage
      volumes:
        - name: project-pv-storage
          persistentVolumeClaim:
            claimName: projects-pv-claim-default
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
