apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: europe-west1-docker.pkg.dev/autocode-347209/sandbox/playground-sandbox-api
      context: ./backend
      docker:
        target: production
    - image: europe-west1-docker.pkg.dev/autocode-347209/sandbox/playground-sandbox-fr
      context: ./frontend
      docker:
        target: production
manifests:
  kustomize:
    paths:
      - ./k8s/overlays/production
deploy:
  kubectl: {}
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: europe-west1-docker.pkg.dev/autocode-347209/sandbox/playground-sandbox-api
          context: ./backend
          sync:
            manual:
              - src: src/**/*.ts
                dest: .
          docker:
            target: development
        - image: europe-west1-docker.pkg.dev/autocode-347209/sandbox/playground-sandbox-fr
          context: ./frontend
          sync:
            manual:
              - src: src/**
                dest: .
          docker:
            target: development
      local: {}
    manifests:
      kustomize:
        paths:
          - ./k8s/overlays/local
    deploy:
      kubectl: {}
