apiVersion: skaffold/v4beta11
kind: Config
build:
  artifacts:
    - image: ghcr.io/utwo/sandbox-backend
      context: ./backend
      docker:
        target: production
    - image: ghcr.io/utwo/sandbox-frontend
      context: ./frontend
      docker:
        target: production
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: ghcr.io/utwo/sandbox-backend
          context: ./backend
          sync:
            manual:
              - src: src/**/*.ts
                dest: .
          docker:
            target: development
        - image: ghcr.io/utwo/sandbox-frontend
          context: ./frontend
          sync:
            manual:
              - src: src/**
                dest: .
          docker:
            target: development
      local: {}
    manifests:
      helm:
        releases:
          - name: playground-sandbox
            chartPath: ./k8s/playground-sandbox
            namespace: default
            setValueTemplates:
              backend.image.tag: "{{.IMAGE_TAG_ghcr_io_utwo_sandbox_backend}}@{{.IMAGE_DIGEST_ghcr_io_utwo_sandbox_backend}}"
              frontend.image.tag: "{{.IMAGE_TAG_ghcr_io_utwo_sandbox_frontend}}@{{.IMAGE_DIGEST_ghcr_io_utwo_sandbox_frontend}}"
    deploy:
      kubectl: {}
