apiVersion: skaffold/v2beta28
kind: Config
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: europe-west1-docker.pkg.dev/autocode-347209/sandbox/playground-sandbox
          docker:
            target: development
          sync:
            manual:
              - src: "src/**/*.ts"
                dest: .
        - image: europe-west1-docker.pkg.dev/autocode-347209/sandbox/playground-sandbox-fr
          context: ./../frontend
          docker:
            target: development
          sync:
            manual:
              - src: "src/**"
                dest: .
    deploy:
      kustomize:
        paths: ["./k8s/overlays/local"]

  - name: multicluster-eu
    activation:
      - kubeContext: gke_autocode-347209_europe-west1-b_playground-sandbox
    deploy:
      kustomize:
        paths: ["./k8s/overlays/production-eu"]

  - name: multicluster-us
    activation:
      - kubeContext: gke_autocode-347209_us-central1-b_playground-sandbox-us
    deploy:
      kustomize:
        paths: ["./k8s/overlays/production-us"]

build:
  artifacts:
    - image: europe-west1-docker.pkg.dev/autocode-347209/sandbox/playground-sandbox
      docker:
        target: production
    - image: europe-west1-docker.pkg.dev/autocode-347209/sandbox/playground-sandbox-fr
      context: ./../frontend
      docker:
        target: production
