apiVersion: skaffold/v2beta22
kind: Config
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: node-app
          context: .
          sync:
            manual:
              - src: "src/**/*.ts"
                dest: .

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
