apiVersion: skaffold/v2beta22
kind: Config
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: node-app
          context: .
          sync:
            manual:
              - src: "src/**/*.ts"
                dest: .
        - image: nginx-proxy
          context: ./k8s/nginx

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
portForward:
  - resourceType: service
    resourceName: app-svc
    namespace: default
    port: 8888
    localPort: 8888
  - resourceType: service
    resourceName: nginx
    namespace: default
    port: 80
    localPort: 8088
  - resourceType: service
    resourceName: nginx
    namespace: default
    port: 81
    localPort: 8089
