apiVersion: skaffold/v2beta28
kind: Config
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      artifacts:
        - image: europe-docker.pkg.dev/croapp-dev/teleport/playground-sandbox
          docker:
            target: development
          sync:
            manual:
              - src: "src/**/*.ts"
                dest: .
        - image: europe-docker.pkg.dev/croapp-dev/teleport/playground-sandbox-fr
          context: ./../frontend
          docker:
            target: development
          sync:
            manual:
              - src: "src/**"
                dest: .
    deploy:
      kustomize:
        paths: ["./k8s/overlays/local"]

build:
  artifacts:
    - image: europe-docker.pkg.dev/croapp-dev/teleport/playground-sandbox
      docker:
        target: production
    - image: europe-docker.pkg.dev/croapp-dev/teleport/playground-sandbox-fr
      docker:
        target: production
deploy:
  kustomize:
    paths: ["./k8s/overlays/production"]
