apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: NODE_ENV
              value: production
            - name: APP_ENV
              value: production
            - name: REGION
              value: EU
