{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "playground-sandbox.fullname" . }}
  labels:
    {{- include "playground-sandbox.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  defaultBackend:
    service:
      name: frontend
      port:
        name: http
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: frontend
                port:
                  name: http
    - host: {{ .Values.ingress.apiSubdomain }}.{{ .Values.ingress.domain }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ .Values.ingress.backendService.name }}
                port:
                  name: {{ .Values.ingress.backendService.port }}
    - host: "*.{{ .Values.ingress.projectSubdomain }}.{{ .Values.ingress.domain }}"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nginx
                port:
                  name: ng-sandbox-port
    - host: "*.{{ .Values.ingress.vscodeSubdomain }}.{{ .Values.ingress.domain }}"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nginx
                port:
                  name: ng-vscode-port
{{- end }}
