apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-router
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: quay.io/robszumski/k8s-service-proxy
        name: nginx
