apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
        - name: app
          resources:
            limits:
              memory: 512Mi
              cpu: "300m"
          env:
            - name: NODE_ENV
              value: production
            - name: APP_ENV
              value: production
