apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backendconfig-health-nginx
spec:
  timeoutSec: 600
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /health
    port: 3000
