commonLabels:
  variant: production
resources:
  - ../../base
  - volume.yaml
  - backendconfig.yaml
  - backendconfig-health-nginx.yaml

patchesStrategicMerge:
  - app-deployment.yaml
  - ingress.yaml
  - nginx-cm.yaml
  - volume-claims.yaml
