labels:
  - pairs:
      variant: production
    includeSelectors: true

resources:
  - ../../base
  - volume.yaml
  - backendconfig.yaml
  - backendconfig-health-nginx.yaml

patchesStrategicMerge:
  - app-deployment.yaml
  - ingress.yaml
  - volume-claims.yaml
