apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: projects-pv-claim-default
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: fileserver
  resources:
    requests:
      storage: 1T
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: projects-pv-claim-public
  namespace: public
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeName: fileserver-public
  resources:
    requests:
      storage: 1T
