apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "backendconfig-health-nginx"}'
spec:
  ports:
    - name: ng-sandbox-port
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: ng-vscode-port
      port: 3773
      protocol: TCP
      targetPort: 3773
    - name: ng-health-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  namespace: default
  name: nginx
