apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "playground-sandbox.labels" . | nindent 4 }}
    app: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "playground-sandbox.selectorLabels" . | nindent 4 }}
    app: frontend
